version: 2.1

jobs:
  config_fortigate:
    machine: true
    resource_class: iphonesekino-lab/ciscotest001
    steps:
      - checkout

      # pip/curl を用意
      - run:
          name: "Install Python/pip & curl"
          command: |
            set -euxo pipefail
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip curl ca-certificates
            python3 -m pip install --upgrade pip
            python3 -m pip install requests

      # プロキシの影響を除去（ある場合）
      - run:
          name: "Unset proxies"
          command: |
            unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
            env | grep -i proxy || true

      # HTTP で疎通確認
      - run:
          name: "Sanity: reach FortiGate over HTTP"
          command: |
            set -euxo pipefail
            : "${FGT_HOST:?FGT_HOST is required}"
            PORT="${FGT_PORT:-80}"
            timeout 5 bash -c "cat </dev/null >/dev/tcp/${FGT_HOST}/${PORT}"
            curl -sI "http://${FGT_HOST}:${PORT}/" | head -n1 || true
            echo "HTTP ${PORT} reachable"

      # 実行
      - run:
          name: "Change FortiGate hostname via API (HTTP test)"
          command: |
            set -euo pipefail
            : "${FGT_HOST:?FGT_HOST is required}"
            : "${FGT_API_TOKEN:?FGT_API_TOKEN is required}"
            python3 fortigate_config.py \
              --scheme http \
              --port "${FGT_PORT:-80}" \
              --hostname GP-FortiGate

workflows:
  config:
    jobs:
      - config_fortigate





