version: 2.1

jobs:
  config_cisco:
    machine: true
    resource_class: iphonesekino-lab/ciscotest001   # 自前ランナーで実行
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dIvzWtrElGUvggTmVlPR+PKZCRgFBk21NtDmumXjA4M"

      - run:
          name: Prepare SSH
          command: |
            set -euxo pipefail
            : "${CISCO_HOST:?CISCO_HOST is required}"
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
            # 初回は known_hosts を作る
            ssh-keyscan -T 10 -H "$CISCO_HOST" >> ~/.ssh/known_hosts || true
            # 鍵がエージェントに入っているか確認（デバッグ用）
            ssh-add -L || true

      - run:
          name: Configure Cisco Hostname
          command: |
            set -euxo pipefail
            { printf '%s\n' \
                'terminal length 0' \
                'configure terminal' \
                'hostname GP-Router' \
                'end' \
                'write memory'; } \
            | ssh -tt \
                -o IdentitiesOnly=yes \
                -o StrictHostKeyChecking=no \
                -o PubkeyAcceptedKeyTypes=+ssh-rsa \
                -o HostKeyAlgorithms=+ssh-rsa \
                -o KexAlgorithms=+diffie-hellman-group14-sha1 \
                -o Ciphers=+aes256-cbc \
                admin1@"$CISCO_HOST"

workflows:
  config:
    jobs:
      - config_cisco


