version: 2.1

jobs:
  config_cisco:
    machine: true
    resource_class: iphonesekino-lab/ciscotest001
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dIvzWtrElGUvggTmVlPR+PKZCRgFBk21NtDmumXjA4M"

      - run:
        name: Show the key actually used
        command: |
          set -euxo pipefail
          ssh-add -L || true                     # ここに公開鍵本文が出ます（ssh-rsa …）
          KEY="$(ls -1 ~/.ssh/id_rsa_* | head -n1)"
          echo "Using key: $KEY"
          ssh-keygen -lf "$KEY"                  # ここに SHA256 指紋が出ます
          name: Smoke test (show clock with -vvv)
          command: |
            set -euo pipefail
            : "${CISCO_HOST:?CISCO_HOST is required}"

            # known_hosts（初回）
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
            ssh-keyscan -T 10 -H "$CISCO_HOST" >> ~/.ssh/known_hosts || true

            # どの鍵が入ったか確認＆その鍵を -i で使う
            ssh-add -L || true
            KEY="$(ls -1 ~/.ssh/id_rsa_* | head -n1)"
            echo "Using key: $KEY"

            # ローカルで成功したのと同じオプションでまず疎通確認
            ssh -vvv \
              -i "$KEY" \
              -o IdentitiesOnly=yes \
              -o BatchMode=yes \
              -o StrictHostKeyChecking=accept-new \
              -o PubkeyAcceptedKeyTypes=+ssh-rsa \
              -o HostKeyAlgorithms=+ssh-rsa \
              -o KexAlgorithms=+diffie-hellman-group14-sha1 \
              -o Ciphers=+aes256-cbc \
              admin1@"$CISCO_HOST" "show clock"

      - run:
          name: Configure Cisco Hostname
          command: |
            set -euo pipefail
            KEY="$(ls -1 ~/.ssh/id_rsa_* | head -n1)"
            { printf '%s\r\n' \
              'terminal length 0' \
              'configure terminal' \
              'hostname GP-Router' \
              'end' \
              'write memory'; } \
            | ssh -tt \
                -i "$KEY" \
                -o IdentitiesOnly=yes \
                -o BatchMode=yes \
                -o StrictHostKeyChecking=accept-new \
                -o PubkeyAcceptedKeyTypes=+ssh-rsa \
                -o HostKeyAlgorithms=+ssh-rsa \
                -o KexAlgorithms=+diffie-hellman-group14-sha1 \
                -o Ciphers=+aes256-cbc \
                admin1@"$CISCO_HOST"

workflows:
  config:
    jobs:
      - config_cisco

