version: 2.1

jobs:
  config_fortigate:
    machine: true
    resource_class: iphonesekino-lab/fortigatetest001
    steps:
      - checkout

      - run:
          name: Setup Python virtual environment
          command: |
            set -euo pipefail
            python3 -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip
            pip install requests

      - run:
          name: Change FortiGate hostname via API
          command: |
            set -euo pipefail
            . .venv/bin/activate
            : "${FGT_HOST:?FGT_HOST is required}"
            : "${FGT_API_TOKEN:?FGT_API_TOKEN is required}"
            python fortigate_config.py \
              --scheme https \
              --port "${FGT_PORT:-443}" \
              --hostname "GP-FortiGate"

workflows:
  config:
    jobs:
      - config_fortigate






