version: 2.1

jobs:
  config_fortigate:
    machine: true
    resource_class: iphonesekino-lab/ciscotest001   # ←自前ランナー
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            python3 -m pip install --upgrade pip
            pip install requests
      - run:
          name: Sanity check to FortiGate
          command: |
            set -euxo pipefail
            : "${FGT_HOST:?FGT_HOST is required}"
            # 443/TCP 到達性チェック
            timeout 5 bash -c "cat < /dev/null > /dev/tcp/${FGT_HOST}/443" && echo "443 reachable"
      - run:
          name: Change FortiGate hostname via API
          command: |
            set -euo pipefail
            : "${FGT_HOST:?FGT_HOST is required}"
            : "${FGT_API_TOKEN:?FGT_API_TOKEN is required}"
            python fortigate_config.py --hostname GP-FortiGate

workflows:
  config:
    jobs:
      - config_fortigate



