version: 2.1

jobs:
  config_cisco:
    machine: true
    resource_class: iphonesekino-lab/ciscotest001   # 自前ランナー

    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:dIvzWtrElGUvggTmVlPR+PKZCRgFBk21NtDmumXjA4M"

      - run:
          name: Prepare SSH
          command: |
            set -euxo pipefail
            : "${CISCO_HOST:?CISCO_HOST is required}"

            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts

            # ホスト鍵登録（初回）
            ssh-keyscan -T 10 -H "$CISCO_HOST" >> ~/.ssh/known_hosts || true

            which ssh
            ssh -V
            echo "---- supported ciphers ----"
            ssh -Q cipher | tr '\n' ' ' && echo
            echo "---- effective per-host params ----"
            ssh -G "$CISCO_HOST" | egrep '^(ciphers|kexalgorithms|macs|hostkeyalgorithms)'

            echo "---- keys in agent ----"
            ssh-add -L || true

      # 1) まず疎通だけ確認（詳細ログ付き）
      - run:
          name: Smoke test (show clock with -vvv)
          command: |
            set -euxo pipefail
            ssh -vvv \
              -o IdentitiesOnly=yes \
              -o BatchMode=yes \
              -o PreferredAuthentications=publickey \
              -o PubkeyAuthentication=yes \
              -o StrictHostKeyChecking=accept-new \
              -o Ciphers=aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc \
              -o KexAlgorithms=diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 \
              -o MACs=hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96 \
              -o HostKeyAlgorithms=ssh-rsa \
              -o PubkeyAcceptedKeyTypes=ssh-rsa \
              admin1@"$CISCO_HOST" "show clock"

      # 2) 通ったらコンフィグ投入
      - run:
          name: Configure Cisco Hostname
          command: |
            set -euxo pipefail
            { printf '%s\r\n' \
              'terminal length 0' \
              'configure terminal' \
              'hostname GP-Router' \
              'end' \
              'write memory'; } \
            | ssh -tt \
                -o IdentitiesOnly=yes \
                -o BatchMode=yes \
                -o PreferredAuthentications=publickey \
                -o PubkeyAuthentication=yes \
                -o StrictHostKeyChecking=accept-new \
                -o Ciphers=aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc \
                -o KexAlgorithms=diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 \
                -o MACs=hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96 \
                -o HostKeyAlgorithms=ssh-rsa \
                -o PubkeyAcceptedKeyTypes=ssh-rsa \
                admin1@"$CISCO_HOST"

workflows:
  config:
    jobs:
      - config_cisco
