version: 2.1

jobs:
  config_fortigate:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install curl & jq
          command: |
            sudo apt-get update && sudo apt-get install -y curl jq

      - run:
          name: Change FortiGate hostname via API
          command: |
            set -euxo pipefail
            : "${FGT_HOST:?FGT_HOST is required}"
            : "${FGT_API_TOKEN:?FGT_API_TOKEN is required}"

            curl -k -X PUT "https://${FGT_HOST}/api/v2/cmdb/system/global" \
              -H "Authorization: Bearer ${FGT_API_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{"hostname": "GP-FortiGate"}'

workflows:
  config:
    jobs:
      - config_fortigate

